%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV)
Camera.Width: 640
Camera.Height: 480
Camera.fx: 615.98974609375
Camera.fy: 615.9147338867188
Camera.cx: 317.8431091308594
Camera.cy: 235.17555236816406

Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0
Camera.k3: 0.0

# IR projector baseline times fx (aprox.)
Camera.bf: 40.0

# Camera Field Of View (Needed by DIFODO)
Camera.fovh_degrees: 74.0
Camera.fovv_degrees: 62.0

# Close/Far threshold. Baseline times.
ThDepth: 40.0

# Deptmap values factor
DepthMapFactor: 1000

#--------------------------------------------------------------------------------------------
# DIFODO Parameters
#--------------------------------------------------------------------------------------------
# To see more about these parameteres check https://roboticslaburjc.github.io/2019-tfm-omar-garrido/entries/entry7/

# Depth filter. Only the depth pixel values between the min and max will be considered for
# DIFODO algorithm.
DIFODO.min_depth_value_filter: 0.5
DIFODO.max_depth_value_filter: 4.5

# The downsampling applied to the original image before using DIFODO algorithm.
# Example: An image 640x480 will be 160x120 for DIFODO algorithm. DIFODO compute time is
# based on the input image resolution. For real time (at least 30FPS) a resolution of 320x240
# using ctf_levels = 5 will allow 30ms of computing time approx.
DIFODO.downsample: 4
# The number of pyramid levels (the more the best). From 3-5 there is almost no difference
# on the estimation. Recommmended value is 5.
DIFODO.ctf_levels: 5
# 1 to use it, 0 to not use it
DIFODO.fast_pyramid: 0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 2.0

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 5

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum threshold.
# You can lower these values if your images have low contrast
ORBextractor.thresholdFAST: 25

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0

#--------------------------------------------------------------------------------------------
# ROS Parameters
#--------------------------------------------------------------------------------------------
ROS.CameraTopic: "/camera/color/image_raw"
ROS.DepthTopic: "/camera/aligned_depth_to_color/image_raw"
ROS.IMUTopic: "/imu_data"
ROS.BaseFrame: "odom"
ROS.CameraFrame: "camera_link"
# 1 == true, 0 == false
ROS.UseImagesTimeStamps: 1